### ISSUE TITLE
fluffos can't be compiled under CYGWIN with binutils 2.28

### ISSUE THREAD

**Issue by seikichin** [fluffos/fluffos#386]
fluffos没办法用cygwin最新版本编译
提示错误
lto1：有些警告被当作是错误
lto-wrapper: 致命错误：g++ 以返回值 1 退出
编译中断。
/usr/lib/gcc/x86_64-pc-cygwin/6.3.0/../../../../x86_64-pc-cygwin/bin/ld: error: lto-wrapper failed
collect2: 错误：ld 返回 1
make: *** [Makefile:194：driver.exe] 错误 1
collect2: 致命错误：ld 以信号 11 [Segmentation fault], core dumped 退出。
编译中断。
/usr/lib/gcc/x86_64-pc-cygwin/6.3.0/../../../../x86_64-pc-cygwin/bin/ld: libdriver.a(regexp.o) (.gnu.lto_.inline.d890d39c6b5609be): Section flag STYP_DSECT (0x1) ignored
/usr/lib/gcc/x86_64-pc-cygwin/6.3.0/../../../../x86_64-pc-cygwin/bin/ld: libdriver.a(regexp.o) (.gnu.lto_.inline.d890d39c6b5609be): Section flag STYP_COPY (0x10) ignored
/usr/lib/gcc/x86_64-pc-cygwin/6.3.0/../../../../x86_64-pc-cygwin/bin/ld: libdriver.a(regexp.o) (.gnu.lto_.inline.d890d39c6b5609be): Section flag IMAGE_SCN_LNK_OTHER (0x100) ignored
/usr/lib/gcc/x86_64-pc-cygwin/6.3.0/../../../../x86_64-pc-cygwin/bin/ld: libdriver.a(regexp.o) (.gnu.lto_.inline.d890d39c6b5609be): Section flag IMAGE_SCN_MEM_NOT_CACHED (0x4000000) ignored

gcc-core6.3.0.2
gcc-g++6.3.0.2

**Comment by seikichin** [comment]
编译时cygwin默认安装均为最新版
# python 
# gcc-core  6.3.0.2       //官方推荐4.8.2-1版本在cygwin里已经不到
# gcc-g++  6.3.0.2      //官方推荐4.8.2-1 版本在cygwin里已经不到
# libstdc++6 4.8.2-1
# make       4.0-2
# m4         1.4.17-1
# libiconv-dev 
# libpcre-dev
# openssl 
# libcrypt-devel
# bison
# dos2unix
# git
# vim (recommended)

**Comment by thefallentree** [comment]
confirmed , something is wrong in regard  with LD linking FLTO objects. I need to test more to find a cure

**Comment by thefallentree** [comment]
This issue can be worked around by installing binutils 2.25 in CYGWIN. 

I send a email to ask cygwin people to help with latest version 
https://cygwin.com/ml/cygwin/2017-09/msg00278.html

**Comment by seikichin** [comment]
done

**Comment by thefallentree** [comment]
should be fixed now upgraded to binutils 2.29.1 https://cygwin.com/ml/cygwin/2017-10/msg00065.html

**Comment by Shea690901** [comment]
**Should** is the correct choice of words, unfortunately it is still a problem ....

But thanks for the tip with version 2.25, I'll try that next

(This issue should probably be reopend for easier reference until this issue is truly in the past...)
